name: Build Image

on:
  push:
      tags:
          - v*

jobs:
  build:
      if: github.event.base_ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      name: Build image job
      
      steps:
          - name: Checkout master
            uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
          - name: Get version
            id: get_version
            if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'Binaryify/NeteaseCloudMusicApi')
            run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          - name: Set Swap Space
            uses: pierotofy/set-swap-space@master
            with:
              swap-size-gb: 10
          - name: Build and publish image
            uses: ilteoood/docker_buildx@master
            if: startsWith(github.ref, 'refs/tags/') && startsWith(github.repository, 'Binaryify/NeteaseCloudMusicApi')
            with:
              publish: true
              imageName: binaryify/netease_cloud_music_api # dockerid/imageName
              platform: linux/ppc64le,linux/arm64,linux/amd64,linux/arm/v6,linux/arm/v7 # 你准备构建的镜像平台
              tag: latest,${{ steps.get_version.outputs.VERSION }}
              dockerUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid 在setting创建secrets name=DOCKER_USERNAME  value=dockerid
              dockerPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password,在setting创建secrets name=DOCKER_PASSWORD  value=dockerpassword
